name: Feature to Dev CI/CD

on:
  push:
    branches:
      - dev  # Trigger when changes are pushed to the dev branch

jobs:
  build-test-and-create-pr:
    name: Build, Test, and Create PR for Dev to Main
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js for Backend
      - name: Set up Node.js for Backend
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 3: Install Backend Dependencies
      - name: Install Backend Dependencies
        working-directory: ./backend
        run: npm install

      # Step 4: Install Frontend Dependencies
      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: npm install

      # Step 5: Run Backend Unit Tests
      - name: Run Backend Unit Tests
        working-directory: ./backend
        run: npm test

      # Step 6: Run Frontend Unit Tests
      - name: Run Frontend Unit Tests
        working-directory: ./frontend
        run: npm test

      # Step 7: Create a Pull Request to Merge Dev into Main
      - name: Create Pull Request from Dev to Main
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: main               # Target branch (main)
          commit-message: "Auto-merge Dev into Main"
          title: "Auto PR: Merge Dev into Main"
          body: |
            This Pull Request merges changes from `dev` into `main`.
