name: Feature to Dev CI/CD

on:
  push:
    branches:
      - dev  # Trigger when changes are pushed to the dev branch

jobs:
  build-test-and-merge:
    name: Build, Test, and Merge Dev into Main
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js for Backend
      - name: Set up Node.js for Backend
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 3: Install Backend Dependencies
      - name: Install Backend Dependencies
        working-directory: ./backend
        run: npm install

      # Step 4: Install Frontend Dependencies
      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: npm install

      # Step 5: Run Backend Unit Tests
      - name: Run Backend Unit Tests
        working-directory: ./backend
        run: npm test

      # Step 6: Run Frontend Unit Tests
      - name: Run Frontend Unit Tests
        working-directory: ./frontend
        run: npm test

      # Step 7: Merge Dev into Main
      - name: Merge Dev into Main
        uses: devmasx/merge-branch@v1.3.0
        with:
          type: merge            # Type de fusion : merge, squash, ou rebase
          from_branch: dev       # Branche source
          target_branch: main    # Branche cible
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
