name: Main to Docker CI/CD

on:
  workflow_run:
    workflows: ["CI/CD for Dev to Main"]
    types:
      - completed

jobs:
  build-and-test:
    name: Build, Test, and Run E2E
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js (for both backend and frontend)
      - name: Set up Node.js for Backend
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Set up Node.js for Frontend
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 3: Install dependencies for frontend and backend
      - name: Install Backend Dependencies
        working-directory: ./backend
        run: npm install

      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: npm install

      - name: Install e2e Dependencies
        working-directory: ./e2e-tests
        run: npm install

      # Step 4: Run Unit Tests for both backend and frontend
      - name: Run Backend Unit Tests
        working-directory: ./backend
        run: npm test

      - name: Run Frontend Unit Tests
        working-directory: ./frontend
        run: npm test

      - name: Build and Push Docker Images
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        docker build -t $DOCKER_USERNAME/backend ./backend
        docker build -t $DOCKER_USERNAME/frontend ./frontend
        docker push $DOCKER_USERNAME/backend
        docker push $DOCKER_USERNAME/frontend